# Generated by Django 3.0.8 on 2020-11-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking_in',
            name='active',
        ),
    ]
