# Generated by Django 3.0.8 on 2020-11-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_remove_parking_in_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='parking_out',
        ),
    ]
